title: DHNB2023 - NWA Workshop
description: Documentation and resources for the NWA workshop during DHNB2023.
remote-theme: just-the-docs

url: https://nlnwa.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
